version: "2"
services:

  consul:
    command: -server -bootstrap
    image: gliderlabs/consul-server
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "53"

  nginx:
    image: openlmis/nginx:1
    ports:
      - "80:80"
    env_file: .local-web-test-env
    depends_on: [consul]

  stockmanagement:
    image: openlmis/stockmanagement
    env_file: .local-web-test-env
    environment:
      JAVA_OPTS: '-Dspring.jpa.properties.hibernate.hbm2ddl.import_files=/bootstrap.sql,file:///demo-data/data.sql'
    depends_on: [nginx,auth,referencedata]

  stockmanagement-ui:
    image: openlmis/dev-ui:2
    ports:
      - "9000:9000"
      - "9876:9876"
    working_dir: /app
    volumes:
      - '..:/app'
    volumes_from:
      - auth-ui
      - referencedata-ui
      - ui-components
      - ui-layout
      - requisition-ui
    depends_on:
      - auth-ui
      - requisition-ui
      - referencedata-ui
      - ui-components
      - ui-layout
      - stockmanagement

  requisition-ui:
    image: openlmis/requisition-ui:4.0.0
    volumes:
      - '/openlmis-requisition-ui'

  auth-ui:
    image: openlmis/auth-ui:4.0.0
    volumes:
      - '/openlmis-auth-ui'
  referencedata-ui:
    image: openlmis/referencedata-ui:4.0.0
    volumes:
      - '/openlmis-referencedata-ui'
  ui-components:
    image: openlmis/ui-components:4.0.0
    volumes:
      - '/openlmis-ui-components'
  ui-layout:
    image: openlmis/ui-layout:4.0.0
    volumes:
      - '/openlmis-ui-layout'

  auth:
    image: openlmis/auth
    env_file: .local-web-test-env
    environment:
      JAVA_OPTS: '-Dflyway.locations=classpath:db/migration,filesystem:/demo-data'
    depends_on: [consul,log,db]

  referencedata:
    image: openlmis/referencedata
    env_file: .local-web-test-env
    environment:
      JAVA_OPTS: '-Dflyway.locations=classpath:db/migration,filesystem:/demo-data'
    depends_on: [consul,log,db]

  db:
    image: openlmis/postgres:9.6
    ports:
      - "5432:5432"
    env_file: .local-web-test-env

  log:
    image: openlmis/rsyslog:1

volumes:
  gradlecache:
    external: false
